server:
  port: 8012


spring:
  profile: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cursomc?useSSL=true
    username: root
    password: devdojo
  jpa:
    properties:
      hobernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: false

jwt:
  secret: dev
  expiration: 600000
